# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ff6a284eeae41a1719ec4e901ffbf93e14e9d01f1f23e8ebe8a52c992b5a4e88a6f098e5534b5a686878c1dfc91c50340ba1a4bbf4a36e00f994a9a46626dc

test:
  secret_key_base: 8792734f1d30e9300be5e237b26cef5514d649d0601247cd7de68ff0be10680c18f048800cb423813e32527f2d1cd9109282312c2ae973b0da9790af83bbcc9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
